### ISSUE TITLE
wat happened

### ISSUE THREAD

**Issue by AfterNetwork** [Smile-js/Smile.js#1]

**Comment by smileycreations15** [comment]
i was trying to get github to enable jump-to-definition on my repo

**Comment by AfterNetwork** [comment]
meet me in AFP (the old org)

**Comment by smileycreations15** [comment]
why

**Comment by AfterNetwork** [comment]
because it now is VR

**Comment by smileycreations15** [comment]
vr will be dome internally

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@AfterNetwork discord

open it
new announcement

**Comment by smileycreations15** [comment]
@AfterNetwork discord

open it
new announcement

**Comment by AfterNetwork** [comment]
solved
