### ISSUE TITLE
100 DOWNLOADS ON NPM!

### ISSUE THREAD

**Issue by AfterNetwork** [Smile-js/Smile.js#2]
We need an update NOW. think of something

**Comment by smileycreations15** [comment]
new features:
browser identification (to be used for duplication-checking in polls)
new chess engine
devtools detection

**Comment by smileycreations15** [comment]
@AfterNetwork also can you help with scratchbux?

**Comment by AfterNetwork** [comment]
sure

**Comment by smileycreations15** [comment]
@afternetwork discord

**Comment by AfterNetwork** [comment]
> @AfterNetwork discord

no

**Comment by AfterNetwork** [comment]
i can't use discord today

**Comment by smileycreations15** [comment]
Why

**Comment by AfterNetwork** [comment]
i might get in trouble and yeah

**Comment by smileycreations15** [comment]
Ohhh

**Comment by smileycreations15** [comment]
Ok you now need to apply to ScratchBux @afternetwork

**Comment by AfterNetwork** [comment]
I have a NPM account

**Comment by AfterNetwork** [comment]
@smileycreations15 make a collaborator on smile.js (NPM)

**Comment by smileycreations15** [comment]
Ok

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@afternetwork wat is ur npm username

**Comment by smileycreations15** [comment]
@afternetwork discord

**Comment by smileycreations15** [comment]
@afternetwork discord

**Comment by AfterNetwork** [comment]
afternetwork

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by AfterNetwork** [comment]
y

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by smileycreations15** [comment]
@AfterNetwork discord

HEEEEY

**Comment by smileycreations15** [comment]
@AfterNetwork discord

HEEEEY

**Comment by smileycreations15** [comment]
@AfterNetwork discord

HEEEEY + hey

**Comment by AfterNetwork** [comment]
no. I am NEVER doing it again

**Comment by smileycreations15** [comment]
@AfterNetwork now give some ideas.

**Comment by AfterNetwork** [comment]
easy. https://dictionaryapi.com/products/api-collegiate-thesaurus

**Comment by smileycreations15** [comment]
@AfterNetwork not so fast. we will not depend on api's

**Comment by AfterNetwork** [comment]
gotta work on a random number generator in a js file, wanna help me?

**Comment by smileycreations15** [comment]
@AfterNetwork yup!

**Comment by smileycreations15** [comment]
create random.js in modules

**Comment by AfterNetwork** [comment]
OMG.

**Comment by AfterNetwork** [comment]
CASE CLOSED.

**Comment by smileycreations15** [comment]
whatt

**Comment by AfterNetwork** [comment]
angry

**Comment by AfterNetwork** [comment]
put this in AFP

**Comment by smileycreations15** [comment]
why

**Comment by smileycreations15** [comment]
it is actually neither in smileycreations or AFP

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
because im lonley

**Comment by smileycreations15** [comment]
@AfterNetwork you still get to be a contributor. we should also merge inspire.js with this. also actually everyone contributes to projects owned by a single person.

**Comment by AfterNetwork** [comment]
WE SHOULD MAKE A SMILE.JS ORG AND MAKE A REPO WITH A DOCUMENATION OF SMILE.JS! BINGO!

**Comment by smileycreations15** [comment]
YUP!!!!!!!!!!!!!!!!!!!

**Comment by AfterNetwork** [comment]
There.
I left discord and scratch.
bye
bye

**Comment by smileycreations15** [comment]
idc

**Comment by smileycreations15** [comment]
@AfterNetwork discord

**Comment by AfterNetwork** [comment]
bob ross

**Comment by smileycreations15** [comment]
@AfterNetwork get on discord

**Comment by AfterNetwork** [comment]
closed for new stuff
